name: workflow 
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: upload to s3
        run: |
          aws s3 cp airbnbproject.py s3://airbnbproject-group4vita/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name my-stack-name \
            --template-file .github/workflows/CFT.yaml \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              InputFilePath1="s3://airbnbproject-group4vita/raw/geojson/airbnb-listings.csv" \
              InputFilePath2="s3://airbnbproject-group4vita/raw/geojson/airbnb-listings.geojson" \
              OutputFilePath="s3://airbnbproject-group4vita/raw/geojson/output/" \
              SubnetId="${{ secrets.AWS_SUBNET_ID }}"
              LogBucket="airbnbproject-group4vita"

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
